[package]
name = "embed-sdk"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { package = "client-sdk-rs-common", path = "../../client-sdk-rs/common" }

serde = { version = "1.0.163", features = ["derive"] }
smol_str = { version = "0.2.0", features = ["serde"] }
timestamp = { package = "iso8601-timestamp", version = "0.2" }
serde_shims = { version = "0.2", features = ["bitflags"] }

schemars = { version = "0.8.12", optional = true }
thin-vec = { version = "0.2.12", optional = true, features = ["serde"] }
typed-builder = { version = "0.14.0", optional = true }
bitflags = "1.2"

[features]
default = ["thin-vec"]
schemars = ["dep:schemars", "common/schemars"]
